//! TPM 2.0 constants.  Section numbers refer to the TPM 2.0 Library
//! Specification, Part 2 "Structures", revision 1.59.

// ---- §6.9 TPM_ST (structure tags) -------------------------------------------
/// Command/response tag: no authorization sessions present.
pub const TPM_ST_NO_SESSIONS: u16 = 0x8001;
/// Command/response tag: authorization area present.
pub const TPM_ST_SESSIONS: u16 = 0x8002;
/// `TPMS_ATTEST.type` for a `TPM2_Quote` attestation.
pub const TPM_ST_ATTEST_QUOTE: u16 = 0x8018;
/// Tag of a `TPMT_TK_CREATION` ticket.
pub const TPM_ST_CREATION: u16 = 0x8021;

// ---- §6.2 TPM_GENERATED --------------------------------------------------------
/// Magic that starts every `TPMS_ATTEST` ("\xffTCG").
pub const TPM_GENERATED_VALUE: u32 = 0xff54_4347;

// ---- §6.5.2 TPM_CC (command codes) --------------------------------------------
/// `TPM2_CreatePrimary`.
pub const TPM_CC_CREATE_PRIMARY: u32 = 0x0000_0131;
/// `TPM2_Startup`.
pub const TPM_CC_STARTUP: u32 = 0x0000_0144;
/// `TPM2_Quote`.
pub const TPM_CC_QUOTE: u32 = 0x0000_0158;
/// `TPM2_FlushContext`.
pub const TPM_CC_FLUSH_CONTEXT: u32 = 0x0000_0165;
/// `TPM2_PCR_Read`.
pub const TPM_CC_PCR_READ: u32 = 0x0000_017E;
/// `TPM2_PCR_Extend`.
pub const TPM_CC_PCR_EXTEND: u32 = 0x0000_0182;

// ---- §6.3 TPM_ALG_ID ------------------------------------------------------------
/// RSA.
pub const TPM_ALG_RSA: u16 = 0x0001;
/// SHA-1.
pub const TPM_ALG_SHA1: u16 = 0x0004;
/// SHA-256.
pub const TPM_ALG_SHA256: u16 = 0x000B;
/// SHA-384.
pub const TPM_ALG_SHA384: u16 = 0x000C;
/// SHA-512.
pub const TPM_ALG_SHA512: u16 = 0x000D;
/// Null algorithm / "no scheme".
pub const TPM_ALG_NULL: u16 = 0x0010;
/// ECDSA signature scheme.
pub const TPM_ALG_ECDSA: u16 = 0x0018;
/// ECC asymmetric algorithm.
pub const TPM_ALG_ECC: u16 = 0x0023;

// ---- §6.4 TPM_ECC_CURVE -------------------------------------------------------
/// NIST P-256 (secp256r1).
pub const TPM_ECC_NIST_P256: u16 = 0x0003;

// ---- §7.4 TPM_RH (permanent handles) -----------------------------------------
/// Owner (storage) hierarchy.
pub const TPM_RH_OWNER: u32 = 0x4000_0001;
/// Null hierarchy.
pub const TPM_RH_NULL: u32 = 0x4000_0007;
/// Password authorization "session" handle (`TPM_RS_PW`).
pub const TPM_RS_PW: u32 = 0x4000_0009;
/// Endorsement hierarchy.
pub const TPM_RH_ENDORSEMENT: u32 = 0x4000_000B;
/// Platform hierarchy.
pub const TPM_RH_PLATFORM: u32 = 0x4000_000C;

// ---- §7.3 TPM_HT / handle ranges -------------------------------------------------
/// First transient object handle (`TPM_HT_TRANSIENT << 24`).
pub const TRANSIENT_FIRST: u32 = 0x8000_0000;

// ---- §6.10 TPM_SU -------------------------------------------------------------------
/// `TPM_SU_CLEAR`.
pub const TPM_SU_CLEAR: u16 = 0x0000;
/// `TPM_SU_STATE`.
pub const TPM_SU_STATE: u16 = 0x0001;

// ---- §8.3 TPMA_OBJECT ------------------------------------------------------------
/// Key's sensitive area may not leave the TPM in which it was created.
pub const TPMA_OBJECT_FIXED_TPM: u32 = 1 << 1;
/// Object is flushed on `TPM2_Startup(CLEAR)`.
pub const TPMA_OBJECT_ST_CLEAR: u32 = 1 << 2;
/// Parent may not be changed.
pub const TPMA_OBJECT_FIXED_PARENT: u32 = 1 << 4;
/// Sensitive data generated by the TPM.
pub const TPMA_OBJECT_SENSITIVE_DATA_ORIGIN: u32 = 1 << 5;
/// `authValue` may be used for USER role authorization.
pub const TPMA_OBJECT_USER_WITH_AUTH: u32 = 1 << 6;
/// ADMIN role requires a policy.
pub const TPMA_OBJECT_ADMIN_WITH_POLICY: u32 = 1 << 7;
/// Object is not subject to dictionary-attack protection.
pub const TPMA_OBJECT_NO_DA: u32 = 1 << 10;
/// Key may only sign/decrypt TPM-generated structures (needed for Quote).
pub const TPMA_OBJECT_RESTRICTED: u32 = 1 << 16;
/// Private portion may be used to decrypt.
pub const TPMA_OBJECT_DECRYPT: u32 = 1 << 17;
/// Private portion may be used to sign.
pub const TPMA_OBJECT_SIGN_ENCRYPT: u32 = 1 << 18;

/// Attributes used for the fixed signing-key template in
/// [`crate::cmd::create_primary_ecc_p256`]: `fixedTPM | fixedParent |
/// sensitiveDataOrigin | userWithAuth | restricted | sign` = `0x00050072`.
pub const SIGNING_KEY_ATTRIBUTES: u32 = TPMA_OBJECT_FIXED_TPM
    | TPMA_OBJECT_FIXED_PARENT
    | TPMA_OBJECT_SENSITIVE_DATA_ORIGIN
    | TPMA_OBJECT_USER_WITH_AUTH
    | TPMA_OBJECT_RESTRICTED
    | TPMA_OBJECT_SIGN_ENCRYPT;

// ---- §8.4 TPMA_SESSION -----------------------------------------------------------
/// `continueSession` bit.
pub const TPMA_SESSION_CONTINUE_SESSION: u8 = 0x01;

// ---- §6.6 TPM_RC --------------------------------------------------------------------
/// Success.
pub const TPM_RC_SUCCESS: u32 = 0x000;
/// `TPM_RC_INITIALIZE`: TPM not initialized by `TPM2_Startup` *or* `TPM2_Startup`
/// sent twice (`RC_VER1 + 0x000`).
pub const TPM_RC_INITIALIZE: u32 = 0x100;
/// `RC_WARN`: base of the warning-class (format-zero) response codes.
pub const RC_WARN: u32 = 0x900;
/// `TPM_RC_YIELDED`: the command was yielded; resend it.
pub const TPM_RC_YIELDED: u32 = RC_WARN + 0x008;
/// `TPM_RC_NV_RATE`: NV rate-limited; resend after a delay.
pub const TPM_RC_NV_RATE: u32 = RC_WARN + 0x020;
/// `TPM_RC_RETRY`: "the TPM was not able to start the command"; resend the
/// identical command.  libtpms/swtpm returns this exactly once for the first
/// command that touches the clock/orderly NV state after `TPM2_Startup`
/// (observed: the first `TPM2_Quote`).
pub const TPM_RC_RETRY: u32 = RC_WARN + 0x022;
/// `TPM_RC_NV_UNAVAILABLE`: NV is not available; resend later.
pub const TPM_RC_NV_UNAVAILABLE: u32 = RC_WARN + 0x023;

// ---- Sizes --------------------------------------------------------------------------------
/// Size of the command header `tag(2) + size(4) + cc(4)`.
pub const COMMAND_HEADER_SIZE: usize = 10;
/// Size of the response header `tag(2) + size(4) + rc(4)`.
pub const RESPONSE_HEADER_SIZE: usize = 10;
/// SHA-256 output size.
pub const SHA256_DIGEST_SIZE: usize = 32;
/// P-256 coordinate / scalar size.
pub const P256_COORD_SIZE: usize = 32;
/// Largest `sizeofSelect` accepted when parsing (`PCR_SELECT_MAX`, Part 2 §10.6.1).
pub const PCR_SELECT_MAX: usize = 4;
/// `sizeofSelect` used when building selections: 3 bytes = 24 PCRs
/// (`PCR_SELECT_MIN`, matching `IMPLEMENTATION_PCR = 24`).
pub const PCR_SELECT_MIN: usize = 3;
/// Maximum number of digests `TPM2_PCR_Read` returns in one call
/// (`TPML_DIGEST.digests[8]`, Part 2 §10.9.4).
pub const PCR_READ_MAX_DIGESTS: usize = 8;
/// Largest hash output we store (SHA-512).
pub const MAX_DIGEST_SIZE: usize = 64;
